### ISSUE TITLE
请求时间总计耗时疑问

### ISSUE THREAD

**Issue by Baoge2012** [PixelCyber/Thor#102]
请问这个总计耗时是哪几个阶段的耗时？这个请求排队时间是指在本机上排队的时间吗？
![531551272134_ pic_hd](https://user-images.githubusercontent.com/2555197/53491745-187e8a00-3ad2-11e9-949e-f5fc562bc7a9.jpg)

![541551272135_ pic_hd](https://user-images.githubusercontent.com/2555197/53491729-10bee580-3ad2-11e9-81c8-b7c52bb22fa1.jpg)

**Comment by PixelCyber** [comment]
请求排队 = thor 接收到app请求连接 到 thor 把开始发送请求到远端 的时间
总计耗时是所有阶段的并发消耗最大时间跨度，因为有的阶段是并发进行的，所以时间不是直接每个阶段相加
