### ISSUE TITLE
申请测试版 1.3.6

### ISSUE THREAD

**Issue by xie0027** [PixelCyber/Thor#104]
申请测试版   已购买  国区 xie0027@gmail.com

**Comment by PixelCyber** [comment]
暂未开放

**Comment by xie0027** [comment]
那要什么时候开放吧  我看好多人都用上1.3.6  6能不能让我一直用TF版啊

**Comment by xie0027** [comment]
1.3.5很多包抓不到  消息体还乱码  每次都要导入到shu里面改后缀  很麻烦啊
