### ISSUE TITLE
安装了测试版，然后买了正版安装之后闪退

### ISSUE THREAD

**Issue by Jasonliu1993** [PixelCyber/Thor#105]
先安转了公测版，然后买了app store上的正版并且自动安装之后就无法打开了，每次阅读完条款就闪退，用不了

**Comment by PixelCyber** [comment]
先把 tf 版删除后再安装商店版呢?

**Comment by Jasonliu1993** [comment]
我把app删除，tf里面的信息也删掉，重启手机再安装，还是阅读完协议就闪退了

**Comment by PixelCyber** [comment]
beta@pixelcyber.com 方便的话。给我发邮件，这里回复太慢了
