### ISSUE TITLE
能否添加非80端口的http报文监控

### ISSUE THREAD

**Issue by dengbotao** [PixelCyber/Thor#108]
能否预留个端口参数，可以监控其他端口的http报文？

**Comment by dake** [comment]
支持所有端口的http啊………如果流量不走系统http代理就没办法抓到

Dake

**Comment by dengbotao** [comment]
嗯，确实都可以抓到。请教下，开启了thor，为什么有的app会不走系统的代理呢？

**Comment by dake** [comment]
不走系统http代理的情况一般是app的网络框架没有使用系统提供的网络接口，而是自己使用了三方从底层实现的网络框架，这样系统就没办法追踪

Dake
