### ISSUE TITLE
现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。

### ISSUE THREAD

**Issue by Hwatu** [PixelCyber/Thor#115]
现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。失去原有价值，希望能有所突破，不然购买后没多大价值了

**Comment by dake** [comment]
无法突破，科学原理

Dake

**Comment by Jsbox3** [comment]
你只是不想搞罢了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dake <notifications@github.com>
发送时间: 2019年7月24日 12:03
收件人: PixelCyber/Thor <Thor@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[PixelCyber/Thor] 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。 (#115)



无法突破，科学原理
 
 Dake

**Comment by dake** [comment]
打扰了

Dake

**Comment by Jsbox3** [comment]
睡了
发自我的 iPad

------------------ 原始邮件 ------------------
发件人: Dake <notifications@github.com>
发送时间: 2019年7月24日 12:22
收件人: PixelCyber/Thor <Thor@noreply.github.com>
抄送: Jsbox3 <1870075348@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[PixelCyber/Thor] 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。 (#115)



打扰了
 
 Dake

**Comment by dake** [comment]
要相信科学

Dake

**Comment by Hwatu** [comment]
> 要相信科学 Dake
> […](#)
> 在 2019年7月24日，12:27，Jsbox3 ***@***.***> 写道： 睡了 发自我的 iPad ------------------ 原始邮件 ------------------ 发件人: Dake ***@***.***> 发送时间: 2019年7月24日 12:22 收件人: PixelCyber/Thor ***@***.***> 抄送: Jsbox3 ***@***.***>, Comment ***@***.***> 主题: 回复：[PixelCyber/Thor] 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。 (#115) 打扰了 Dake > 在 2019年7月24日，12:05，Jsbox3 ***@***.***> 写道： > > 你只是不想搞罢了 > > > > 发自我的iPhone > > > ------------------ 原始邮件 ------------------ > 发件人: Dake ***@***.***> > 发送时间: 2019年7月24日 12:03 > 收件人: PixelCyber/Thor ***@***.***> > 抄送: Subscribed ***@***.***> > 主题: 回复：[PixelCyber/Thor] 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。 (#115) > > > > 无法突破，科学原理 > > Dake > > > 在 2019年7月24日，11:18，Lately ***@***.***> 写道： > > > > 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。失去原有价值，希望能有所突破，不然购买后没多大价值了 > > > > — > > You are receiving this because you are subscribed to this thread. > > Reply to this email directly, view it on GitHub, or mute the thread. > > — > You are receiving this because you are subscribed to this thread. > Reply to this email directly, view it on GitHub, or mute the thread. > — > You are receiving this because you commented. > Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

ssl-kill-switch2 了解一下，只有越狱了才可以，不知道软件能不能hook,修改判断值或绕过

**Comment by dake** [comment]
> > 要相信科学 Dake
> > […](#)
> > 在 2019年7月24日，12:27，Jsbox3 _**@**_._**> 写道： 睡了 发自我的 iPad ------------------ 原始邮件 ------------------ 发件人: Dake _**@**_.**_> 发送时间: 2019年7月24日 12:22 收件人: PixelCyber/Thor _**@**_._**> 抄送: Jsbox3 _**@**_.**_>, Comment _**@**_._**> 主题: 回复：[PixelCyber/Thor] 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。 (#115) 打扰了 Dake > 在 2019年7月24日，12:05，Jsbox3 _**@**_.**_> 写道： > > 你只是不想搞罢了 > > > > 发自我的iPhone > > > ------------------ 原始邮件 ------------------ > 发件人: Dake _**@**_._**> > 发送时间: 2019年7月24日 12:03 > 收件人: PixelCyber/Thor _**@**_.**_> > 抄送: Subscribed _**@**_._**> > 主题: 回复：[PixelCyber/Thor] 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。 (#115) > > > > 无法突破，科学原理 > > Dake > > > 在 2019年7月24日，11:18，Lately _**@**_.**_> 写道： > > > > 现在大量APP使用SSL Pinning证书绑定技术，导致抓包无效。失去原有价值，希望能有所突破，不然购买后没多大价值了 > > > > — > > You are receiving this because you are subscribed to this thread. > > Reply to this email directly, view it on GitHub, or mute the thread. > > — > You are receiving this because you are subscribed to this thread. > Reply to this email directly, view it on GitHub, or mute the thread. > — > You are receiving this because you commented. > Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> ssl-kill-switch2 了解一下，只有越狱了才可以，不知道软件能不能hook,修改判断值或绕过

当然不能，审核员又不是喝稀饭的，只能越狱机上搞搞，而且跟thor 也扯不上关系。就是单纯地开 ssl kill switch 这个插件
