### ISSUE TITLE
widget中开关有bug

### ISSUE THREAD

**Issue by Mr-WK** [PixelCyber/Thor#29]
开着别的梯子，若从weight中开启thor，会打不开，只能进软件打开，关闭同理！

**Comment by PixelCyber** [comment]
@Mr-WK 感谢你的反馈，对我们很有帮助，现在 Thor 初版已上架 AppStore ，我想送你一枚 Thor 的免费兑换码，可有兴趣？求邮箱地址

**Comment by Mr-WK** [comment]
24847538@qq.com，非常感谢您兑换码，感觉您是非常用心的开发者，有问题我会继续反馈，我也会尽一份绵薄之力来向周围朋友推广，最后还衷心的希望软件可以做的更好！

发自我的 iPhone

**Comment by PixelCyber** [comment]
似乎是改好了
