### ISSUE TITLE
POST类型的请求无法看到请求的参数吗？

### ISSUE THREAD

**Issue by 89477337** [PixelCyber/Thor#44]
目前发现就是POST请求，参数无法查看啊~~~咋整。望更新！

**Comment by PixelCyber** [comment]
@89477337 你好， POST 请求参数是指 body 吗？ 如果是的话，无法查看有三种可能：
1. body 本身为空
2. post 请求是失败的
3. 有bug

方便的话，能否贴出想关请求截图和参数 ，以助解决bug 。。感谢你的反馈

**Comment by PixelCyber** [comment]
商店最新版 1.1.1 已经支持https 解析，并且优化了post 请求的抓取率，欢迎尝试
