### ISSUE TITLE
什么时候更新http解析啊

### ISSUE THREAD

**Issue by 1161524972** [PixelCyber/Thor#45]
顺便问一下出了http解析之后可以进行编辑吗 就像电脑上的fd一样

**Comment by 1161524972** [comment]
thor是我第一个买正版的软件 很支持

**Comment by PixelCyber** [comment]
感谢你的支持哦。https 解析大概会在5月份发出 TF。然后再上线，敬请期待。（老用户免费获得，上线 https 版本后会永久提价到 ￥30以上）

**Comment by PixelCyber** [comment]
下周发布 HTTPS TF 测试，欢迎体验
