### ISSUE TITLE
这类专业抓包的工具太少了，已经购买支持了

### ISSUE THREAD

**Issue by ckldy** [PixelCyber/Thor#46]
TCP和UDP以后会支持抓取么？很期待啊，安卓机上的抓包工具很强大，希望苹果上也有

**Comment by PixelCyber** [comment]
感谢支持，TCP,UDP 有计划，但是暂时没在日程上，现在的重点是5月份的 HTTPS 支持。欢迎反馈

**Comment by PixelCyber** [comment]
下周发布 HTTPS TF 测试，欢迎体验

**Comment by ckldy** [comment]
怎么申请TF测试？推特有发布么，给给申请链接

**Comment by PixelCyber** [comment]
发送要申请的邮箱到 beta@pixelcyber.com
