### ISSUE TITLE
有一个关闭后会自动开启的Bug

### ISSUE THREAD

**Issue by YasinTian** [PixelCyber/Thor#50]
当我设置了过滤器里面的"包括域名"之后，当请求为这个域名的时候抓包又会自动打开，但是我已经停止了抓包。不知道是故意这样设置的还是不小心疏忽了，但是当我不想要抓包而又需要使用这几个域名的时候，自动开启抓包对我造成不小的困扰。

**Comment by PixelCyber** [comment]
了解了。。你有没有设置过 『按需开启抓包的域名』？

**Comment by YasinTian** [comment]
好吧。确实是设置了按需启动。😂

**Comment by PixelCyber** [comment]
那我关问题了哦。。。感谢你的反馈。。。有任何问题。。尽管来提 issue。
