### ISSUE TITLE
希望增加原始Request和原始Response的复制功能

### ISSUE THREAD

**Issue by Tu-tu-tu** [PixelCyber/Thor#51]
希望增加原始Request和原始Response的复制功能。

**Comment by PixelCyber** [comment]
原始的是二进制流，而且分HEAD 和 body....直接复制不了的。。必须要先结构化。或者你可以说说自己的用处。。看看有没有别的方式满足

**Comment by Tu-tu-tu** [comment]
![image](http://chuantu.biz/t5/101/1496761205x2890171618.png)
就跟这个一样，能让我拷贝原始的头。
同时希望Thor增加发送自定义数据包的功能。
![image](http://chuantu.biz/t5/101/1496761765x1822611323.png)

**Comment by PixelCyber** [comment]
其实可以间接拷贝整个HEAD：请求行和头 分别单独拷贝，然后拼起来就行了。请求头的整体拷贝入口：请求头 -> 详情 -> 右上角分享


至于修改请求。。就是请求重放和断点调式的功能。。有这个计划。。但是应该是年底的事了。

**Comment by Tu-tu-tu** [comment]
![image](http://chuantu.biz/t5/101/1496803090x466847396.png)
因为我在拷贝一些post的参数的时候会出现乱码，所以希望能拷贝下原始的请求头和响应头。

**Comment by PixelCyber** [comment]
soga。。。了解了。。。我想一下交互 和入口怎么加。。。
但是就算要加，head 可以是结构化后的字符串。。但是body 只能是二进制文件分享出去了。。

**Comment by Tu-tu-tu** [comment]
THX.期待新版本.

**Comment by PixelCyber** [comment]
hi， 我加了一个『文本类型的消息体』可以选择导出原始文件的选项。一会儿要发 TF。你可以申请 TF 体验之。。

**Comment by Tu-tu-tu** [comment]
收到。我已经在测试了。

**Comment by PixelCyber** [comment]
商店最新版的原始数据导出入口足够使用了没？

**Comment by Tu-tu-tu** [comment]
够了。
