### ISSUE TITLE
需要占用VPN来抓包，是否是转发了请求？

### ISSUE THREAD

**Issue by taohy** [PixelCyber/Thor#52]
你好，我这边有个抓包的需求，但是我的请求需要依赖蜂窝移动数据网通道，我想问问，thor的抓包需要占用vpn来抓，是不是说你们把请求给转发了呢，因为你们转发了的话，由于我这边的原因，我的请求肯定是失败的，也就达不到抓包的目的。

**Comment by PixelCyber** [comment]
是的。要转发请求的。但是蜂窝移动数据下。也可以打开VPN 抓包的。除非是像飞行模式那样，没有任何网络就不能开启。

**Comment by PixelCyber** [comment]
啊，似乎明白了你的意思，你是说你的设备需要用wifi 连接到另一台设备共享的网络里，于是用thor 抓不到包了？但是照理说应该是可以抓的，thor 是向系统网口转发请求，如果连了分享网络，也是系统处理，感觉不会有影响。
