### ISSUE TITLE
TF申请

### ISSUE THREAD

**Issue by surge808** [PixelCyber/Thor#60]
549320300@qq.com

**Comment by z5452442** [comment]
1021150497@qq.com  希望TF

**Comment by microxiao** [comment]
holidayone@qq.com
想体验大神的Thor，测试Thor的抓包

**Comment by yinying1341** [comment]
想试试体验下大神的Thor神器.测试Thor的抓包

**Comment by yinying1341** [comment]
忘记写邮箱了yinying1341@vip.qq.com

**Comment by xmlinhua** [comment]
希望体验一下Thor科技成果

**Comment by xmlinhua** [comment]
希望体验一下Thor科技成果

4789510@qq.com

**Comment by aavcc** [comment]
求体验thor
505554673@qq.com

**Comment by jfjjjdi** [comment]
希望Tf，体验一下大神的Thor的抓包效果如何
420123520@qq.com

**Comment by Myxer002** [comment]
希望体验新版1361141860@qq.com

**Comment by dongshiqiang** [comment]
shiqiang0376@hotmail.com

**Comment by mcpeishao** [comment]
942757708@qq.com申请TF

**Comment by wenjie39** [comment]
390845260@qq.com

**Comment by lxw1102** [comment]
已购买正版，但是ios13无法使用，申请TF，203102333@qq.com

**Comment by PixelCyber** [comment]
已购超过 90 天，带上新鲜的苹果收据截图和订单号文本（必须是文本，截图的，将被忽略），和商店内 thor 已购截图到 thor 的反馈邮箱即可申请。（由于工作很忙，可能三四天统一发一次 tf），已经加入体验组 tf 的，请务必在申请已购组后，立即退出体验组 tf （在 testflight 里点 stop），否则将不会收到邀请通知。发送申请的邮箱请尽量不要使用 qq 邮箱，否则可能收不到邀请邮件。

申请已购组 tf 后，对 tf 使用不习惯的，可以自行退出 tf。（tf 版本导出的过滤器格式不能被更低的版本使用）

申请邮箱 beta@pixelcyber.com

Dake
