### ISSUE TITLE
申请公测资格

### ISSUE THREAD

**Issue by leenewb** [PixelCyber/Thor#66]
你好 关注thor 和shu 有一段时间了 我想申请公测资格 然后后期上架后可以将thor和shu捆绑销售吗

leenewb77@gmail.com

**Comment by leenewb** [comment]
已购thor  shu还会上架吗？

**Comment by daizir** [comment]
daizir@icloud.com

**Comment by yinying1341** [comment]
yinying1341@gmail.com
