### ISSUE TITLE
Har file format

### ISSUE THREAD

**Issue by get2joe** [PixelCyber/Thor#69]
Both HTTP Watch and Charles complain about the file format.  In the case of Charles it says the "charles could not open this file due to the following error: Malformed URL: no protocol;"

So far other then this Thor has worked the best for me. The problem is the vendor I need to send the HAR file to uses Charles to open the files.

**Comment by dake** [comment]
Hi, you can try to export the HAR file generated by to "File" app on iOS11, then export export files everywhere in File app, such as iCloud Drive

**Comment by get2joe** [comment]
When I try to use save to file it gives me option of putting in icloud drive and I then get the message The file couldn't be opened because it doesn't exist.

**Comment by dake** [comment]
I meet this error too and try to fix it next version.
You can use my new file manage app - Shu to export har file outside your device.
Shu - Magic File Viewer,   and  it's price off 100% at this moment.
https://itunes.apple.com/app/id1282297037

how to export har file in Thor to other device:
Export har file in Thor > choose Open in Shu > then jump to Shu app and open the recent folder > find the har file you exported, move it to Shared Folder in Shu > then you can use Itunes to export the har file to your computer (By this way, huge har file is easy to export to computer).
