### ISSUE TITLE
申请内测

### ISSUE THREAD

**Issue by CRohr7048** [PixelCyber/Thor#77]
请问还可以申请内测吗
469054080@qq.com

**Comment by huzhihan5** [comment]
邮箱是995925342@qq.com，希望能加入内测

**Comment by lujinxin** [comment]
lu786282441@qq.com
求内测资格

**Comment by 1564940789** [comment]
Shu的内测版，能发给我吗？postmaster@vcxv.cc
谢谢

**Comment by WangShushan** [comment]
大佬，已购thor，shu的内测已过期，能再加嘛？
18650539901@wo.com.cn

**Comment by 1132096857** [comment]
求内测。1132096857@qq.com

**Comment by Myxer002** [comment]
还能申请内测吗？1361141860@qq.com
