### ISSUE TITLE
Anubis 首发限免中,直接下载，请不要预购

### ISSUE THREAD

**Issue by kebyn** [PixelCyber/Thor#82]
Anubis 首发限免中，开始预购（同 Thor 配套，请求重放等 ）
https://itunes.apple.com/app/id1357644265

使用帮助 https://t.me/thornotice
过滤器 https://t.me/f4thor

**Comment by kebyn** [comment]
已经预购的同学， 可以退出 Apple ID ,搜索App ,点击获取,  然后输入Apple ID, 即可下载

**Comment by ipdoor** [comment]
我买了重复套餐，可以退款吗？

**Comment by ipdoor** [comment]
我的apple ID:wwsoot@gmail.com

**Comment by kebyn** [comment]
我不是开发者，而且开发者是没有操作用户的权限，请直接向苹果申请退款
