### ISSUE TITLE
我今天重复购买了两个重复的套餐了。

### ISSUE THREAD

**Issue by ipdoor** [PixelCyber/Thor#86]
可以退一个套餐吗？我退一个单独购买的thor,可以吗？我是学生，太穷啦。麻烦你啦！

**Comment by ipdoor** [comment]
我的app id : wwsoot@gmail.com 万分感激🙏

**Comment by ipdoor** [comment]
I  make a mistake on purchasing this item.Then,I buy another item including this app.so, I already have repeated to buy this app.I am very disappointed with this purchase. I am very looking forward to refund my money which is my first purchase .Thank you very much.

**Comment by PixelCyber** [comment]
@ipdoor 重复购买。。直接跟苹果客服反馈，申请退款，申请原因就是：重复购买，他们会退的。。
