### ISSUE TITLE
建议添加PC端协助功能

### ISSUE THREAD

**Issue by wals** [PixelCyber/Thor#88]
首先赞一个断点调试功能
但是现在随着App功能越来越多,在手机端输入困难的问题也浮现了出来,在手机端输正则表达式那么多特殊字符不是一般的麻烦,而且这么小的输入框写错了也很难发现
希望添加如下功能:在App中内嵌一个Web服务器,内含调试页面,可以在PC端看到实时回显并且可以录入需要调试的字符,实时在手机端生效.这样更方便使用.

**Comment by PixelCyber** [comment]
在准备 thor for mac 中
