### ISSUE TITLE
您好，请问WiFi监听怎么用？

### ISSUE THREAD

**Issue by kshipeng** [PixelCyber/Thor#91]
您好，请问WiFi监听怎么用？

**Comment by PixelCyber** [comment]
用来抓 WIFI 局域内其它设备的流量

**Comment by lin-xin** [comment]
WiFi监听使用步骤是怎么样呢？我打开WiFi监听，另一个设备和当前设备在同个局域网内，但是发起请求，当前设备并没抓到包，需要设置什么吗

**Comment by dake** [comment]
启动抓包后，wifi 监听旁边 有个感叹号，里面有详细说明和操作步骤
